# Configuration for training ResNet18 model on CIFAR-10
model: "resnet18"
dataset: "cifar10"
augmented: true

# Training hyperparameters
epochs: 100
batch_size: 128
lr: 0.1
momentum: 0.9
weight_decay: 0.0001
optimizer: "sgd"

# Learning rate scheduler
scheduler: "step"
step_size: 30
gamma: 0.1

# Data and I/O
data_root: "./data"
checkpoint_dir: "./checkpoints/cifar10_resnet18"
log_dir: "./logs"

# Other options
num_workers: 4
print_freq: 50
save_freq: 10
tensorboard: true
tensorboard_dir: "./runs/cifar10_resnet18"